### ISSUE TITLE
Error parsing translation unit

### ISSUE THREAD

**Issue by dtroitskiy** [cocos2d/bindings-generator#203]
Hello devs!

I'm trying to run genbindings.py, but unfortunately I'm seeing the error, mentioned in the subject.
I'm on Ubuntu 14.04, I followed the instructions and set everything up, I have all python stuff and I have Android NDK r9b, so theoretically it should work, but nope.

Full stack trace is this:

Traceback (most recent call last):
  File "/home/stranger/Library/cocos2d-x-3.3/tools/bindings-generator/generator.py", line 1418, in <module>
    main()
  File "/home/stranger/Library/cocos2d-x-3.3/tools/bindings-generator/generator.py", line 1414, in main
    generator.generate_code()
  File "/home/stranger/Library/cocos2d-x-3.3/tools/bindings-generator/generator.py", line 1087, in generate_code
    self._parse_headers()
  File "/home/stranger/Library/cocos2d-x-3.3/tools/bindings-generator/generator.py", line 1114, in _parse_headers
    tu = self.index.parse(header, self.clang_args)
  File "/home/stranger/Library/cocos2d-x-3.3/tools/bindings-generator/clang/cindex.py", line 2113, in parse
    self)
  File "/home/stranger/Library/cocos2d-x-3.3/tools/bindings-generator/clang/cindex.py", line 2225, in from_source
    raise TranslationUnitLoadError("Error parsing translation unit.")
## Generating lua bindings fails.

Please tell me, maybe I forgot to do something or I can somehow get more detailed info about this error?

**Comment by smshuja** [comment]
I am getting this error while generating javascript bindings.
